services:
  - type: web
    name: eoffice-pro
    runtime: node
    plan: free
    buildCommand: node_modules/.bin/prisma generate && node_modules/.bin/prisma db push --accept-data-loss && npm run build
    startCommand: npm run start
    envVars:
      - key: DATABASE_URL
        value: file:/opt/render/project/src/prisma/dev.db
      - key: NODE_ENV
        value: production
      - key: NEXTAUTH_SECRET
        generateValue: true
      - key: SMTP_USER
        sync: false
      - key: SMTP_PASS
        sync: false
